### ISSUE TITLE
Enable Governance Token Transfer to be Switched off by the DAO

### ISSUE THREAD

**Issue by mijoco-btc** [Clarity-Innovation-Lab/executor-dao#6]
The [SEC criteria for DAO tokens to be considered as securities](https://www.corrcronin.com/2022/02/11/dao-formation-and-securities-laws/#:~:text=The%20SEC%20makes%20clear%20that,the%20founders%20running%20the%20DAO) are that it 
> views DAO-issued tokens as “securities” when (i) the tokens were issued in exchange for money, (ii) purchasers of the token expected the tokens to increase in value, and (iii) the value of the enterprise was linked to the managerial efforts of the founders running the DAO.

If it's possible to imagine scenarios where Executor DAO is used in a not for profit / social enterprise context then a very small change to the Executor DAO could make it very easy for an instance of Executor DAO to meet the SEC criteria and ensure their governance token is never considered a security. 

E.g. a switch in the transfer function;

```(define-public (transfer (amount uint) (sender principal) (recipient principal) (memo (optional (buff 34))))
	(begin
		(asserts! (or (is-eq tx-sender sender) (is-eq contract-caller sender)) err-not-token-owner)
		(asserts! (not (var-get transfer-lock)) err-transfer-is-locked)
		(ft-transfer? edg-token amount sender recipient)
	)
)
```

where `transfer-lock` is a DAO controlled parameter would prevent transfers on marketplaces effectively making it possible for a DAO to run in a pure utility mode.

Note this issue does not impact `edg-transfer` as the DAO itself may need the ability to transfer its own governance token and this would not fall foul of the SEC criteria.

**Comment by mijoco-btc** [comment]
@MarvinJanssen hope this issue is clearer now?

**Comment by MarvinJanssen** [comment]
Doesn't controlling trade make it worse? I honestly wouldn't be opposed to a general transfer lock switch in the reference implementation but at the same time it could break many things. For example, it'll effectively suspend all CEX as well. People won't be able to withdraw tokens because the CEX cannot transfer tokens, etc.. I don't know if such a capability makes it so CEX won't list the tokens in the first place. I always thought that if people wanted such a closed membership token, they could create a custom governance token contract. The reference one we have now ensures that tokens can always freely be transacted by its members. People have also been employing different ways to make it so their governance tokens are not considered securities (PoXL for example) which may be successful. I am not a lawyer so don't quote me on that though. Furthermore, the SEC does not cover the entire world.

**Comment by mijoco-btc** [comment]
Closing this here. There is a newer issue in Ecosystem DAO where discussion of this continues.

See [Bootstrapping the Ecosystem DAO via a Token Sale](https://github.com/Clarity-Innovation-Lab/ecosystem-dao/issues/2)
